language: node_js

node_js:
  - stable

install:
  - npm install

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "Evandoz"
  - git config user.email "evandoz@outlook.com"
  - git add .
  - git commit -m "site update"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - source
env:
 global:
   - GH_REF: github.com/Evandoz/Evandoz.github.io.git
