language: node_js

node_js:
  - stable

install:
  - npm install

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -m "Automatically update from travis-ci"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" ${L_BRANCH}:${O_BRANCH}

branches:
  only:
    - master
env:
  global:
