# Header
nav:
  Archives: archives
  Categories: categories
  Tags: tags
  About: about

# Widget
widgets:
  - profile
  - category
  - footer

# Since
since: 2015

# Set default keywords (Use a comma to separate)
keywords: ""

# Put your favicon.ico into `/themes/swallow/source/` directory.
# Of course you can use a target link instead.
# (E.g. `http://abc.com/favicon.ico` or `css/images/favicon.ico`)
favicon: css/images/favicon.ico
logo: css/images/logo.png
background: css/images/background.jpg

# Links
links:

# Date format
date_format: ''

# Code highlight theme
# Available value:
#    normal | night | night eighties | night blue | night bright
highlight_theme: normal

# Webmaster tools verification setting
google_site_verification: W2AVg5n_ALo21rl9n3ZwS8AuEanZfJkirzrRGLLYvn4
baidu_site_verification: BM2Q3xLpPJ
qihu_site_verification: 573211edf2de02c99d7b255b2c56513c

